server:
  port: 31001
spring:
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
      uri: mongodb://root:root@47.101.134.66:27017
      database: xc_cms
  kafka:
    producer:
      bootstrap-servers: 47.101.134.66:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer